### ISSUE TITLE
[BUG] Modernization Scanner did not provide complete report for workflows

### ISSUE THREAD

**Issue by ooiming** [pnp/sp-dev-modernization#537]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ x ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Expect Document Content Type workflows in document libraries are shown in the report for "Classic workflow usage (detailed)" 

#### Observed Behavior

We are running the modernization scanner tool v 2.17, but still do not see a Document Content Type workflow called "Special Quote" in a document library (called "Cases") shown in the report (did not check all document content type workflows but at least confirm got 1 that is not shown in the report). We are able to see this workflow using SharePoint Designer. 

![DocumentContentTypeWF_SpecialQuotes](https://user-images.githubusercontent.com/72455168/95396359-c2d5aa80-08ce-11eb-8666-9d236db4c5c6.png)

#### Steps to Reproduce

Run "SharePoint.Modernization.Scanner" (v 2.17 - latest version) > auth option: Azure AD App Only (preferred) > scan mode: Classic workflow usage (detailed)
- Checked in both "ModernizationWorkflowScanResults.csv" and "Errors.csv"

**Comment by jansenbe** [comment]
Hi @ooiming , this should be fixed with version 2.18. See #541 for more details.

**Comment by jansenbe** [comment]
Closing as this is fixed

**Comment by ooiming** [comment]
I have re-run using the latest version (v2.18) and this reported workflow (Document Content Type workflow called "Special Quote" in a document library (called "Cases") ) is still not shown in the new report.

**Comment by samGakhar** [comment]
I have re-run the latest version 2.18 at my end as well and still, it's not returning the SPD WFs having a manual trigger.

**Comment by azha23** [comment]
I am running 2.19  for 15612 site collections and the scan is stopping at 50%. Tried running from the UI and also powershell (separate modes) and they are stopping also at 50% with errors. Some of the errors are: "Timeouts" and ""the connection was closed by the server" I am running the scan from my laptop. Any suggestions to get past these issues are welcomed. 
![2021-02-19_10-00-22](https://user-images.githubusercontent.com/49959942/108531236-16ec9480-729c-11eb-9bc2-d9864adeb40c.png)
![2021-02-19_10-01-41](https://user-images.githubusercontent.com/49959942/108531250-19e78500-729c-11eb-9f12-59fb24805486.png)
